/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmi;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BrunoSeven
 */
public class TelaAgente extends javax.swing.JFrame {

    /**
     * Creates new form TelaAgente
     *
     */
    Interface_Servidor interface_server;

    public TelaAgente(Interface_Servidor inter) {

        this.interface_server = inter;
        initComponents();
        this.setVisible(true);
    }

    public void atualiza() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoHotel = new java.awt.TextField();
        campoVoo = new java.awt.TextField();
        lavbelVoo = new java.awt.Label();
        labelHotel = new java.awt.Label();
        campoDataIda = new java.awt.TextField();
        label3 = new java.awt.Label();
        campoDatavolta = new java.awt.TextField();
        labelDataVolta = new java.awt.Label();
        dataCheckin = new java.awt.TextField();
        dataCheckout = new java.awt.TextField();
        checkIn = new java.awt.Label();
        checkOut = new java.awt.Label();
        attVoo = new java.awt.Button();
        labelQuartos = new javax.swing.JLabel();
        labelPessoas = new javax.swing.JLabel();
        attHotel = new java.awt.Button();
        chkPacote = new java.awt.Checkbox();
        nomePacote = new java.awt.TextField();
        campoVooVolta = new java.awt.TextField();
        attPacote = new java.awt.Button();
        nPessoas = new javax.swing.JSpinner();
        nQuartos = new javax.swing.JSpinner();
        Agente = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 48, 62));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        campoHotel.setText("Hotel");
        campoHotel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                setHotel(evt);
            }
        });

        campoVoo.setText("Voo");
        campoVoo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                setVoo(evt);
            }
        });

        lavbelVoo.setForeground(new java.awt.Color(224, 224, 224));
        lavbelVoo.setText("Ida                                 Volta");

        labelHotel.setForeground(new java.awt.Color(224, 224, 224));
        labelHotel.setText("Hotel");

        campoDataIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDataIda(evt);
            }
        });

        label3.setForeground(new java.awt.Color(224, 224, 224));
        label3.setText("DataIda");

        campoDatavolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDataVolta(evt);
            }
        });

        labelDataVolta.setForeground(new java.awt.Color(224, 224, 224));
        labelDataVolta.setText("DataVolta");

        checkIn.setForeground(new java.awt.Color(255, 255, 255));
        checkIn.setName("checkIn"); // NOI18N
        checkIn.setText("checkIn");

        checkOut.setForeground(new java.awt.Color(255, 255, 255));
        checkOut.setText("checkOut");

        attVoo.setFont(attVoo.getFont());
        attVoo.setLabel("Enviar");
        attVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attVooActionPerformed(evt);
            }
        });

        labelQuartos.setForeground(new java.awt.Color(255, 255, 255));
        labelQuartos.setText("Quartos");

        labelPessoas.setForeground(new java.awt.Color(255, 255, 255));
        labelPessoas.setText("Pessoas");

        attHotel.setLabel("Enviar");
        attHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attHotelActionPerformed(evt);
            }
        });

        chkPacote.setForeground(new java.awt.Color(224, 224, 224));
        chkPacote.setLabel("Pacote");
        chkPacote.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkPacote(evt);
            }
        });

        nomePacote.setText("Nome");

        campoVooVolta.setText("Voo Volta");
        campoVooVolta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoVooVoltasetVoo(evt);
            }
        });

        attPacote.setEnabled(false);
        attPacote.setLabel("Enviar");
        attPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attPacoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPessoas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(labelQuartos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(campoVoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoVooVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lavbelVoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(labelDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoDataIda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDatavolta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dataCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(dataCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkPacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attVoo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(attHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(attPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomePacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(campoHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataCheckin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lavbelVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDataIda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDatavolta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(campoVooVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campoVoo.getAccessibleContext().setAccessibleName("campoVoo");
        lavbelVoo.getAccessibleContext().setAccessibleDescription("");
        dataCheckin.getAccessibleContext().setAccessibleName("dataCheckin");
        dataCheckout.getAccessibleContext().setAccessibleName("dataCheckout");
        attVoo.getAccessibleContext().setAccessibleName("enviarVoo");
        attHotel.getAccessibleContext().setAccessibleName("enviarHotel");
        chkPacote.getAccessibleContext().setAccessibleName("Pacote");
        nomePacote.getAccessibleContext().setAccessibleName("nomePacote");

        Agente.setAlignment(java.awt.Label.CENTER);
        Agente.setBackground(new java.awt.Color(0, 0, 0));
        Agente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Agente.setForeground(new java.awt.Color(255, 255, 255));
        Agente.setName("agente"); // NOI18N
        Agente.setText("Agente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Agente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Agente, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Agente.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDataVolta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDataVolta
        // att Data de Volta
    }//GEN-LAST:event_setDataVolta

    private void campoVooVoltasetVoo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoVooVoltasetVoo
        // TODO add your handling code here:
    }//GEN-LAST:event_campoVooVoltasetVoo

    private void setDataIda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDataIda
        //atualiza data de Ida
    }//GEN-LAST:event_setDataIda

    private void chkPacote(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkPacote
        //confirma se eh pacote
        attVoo.setEnabled(!attVoo.isEnabled());
        attHotel.setEnabled(!attHotel.isEnabled());
        attPacote.setEnabled(!attPacote.isEnabled());
    }//GEN-LAST:event_chkPacote

    // invoca metodo attVoo no servidor
    private void attVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attVooActionPerformed

        try {            // ENVIA DADOS À Estrutura de dados
            interface_server.attVoo(chkPacote.getState(), campoDataIda.getText(), campoDatavolta.getText(), campoVoo.getText(), campoVooVolta.getText(), nPessoas.getComponentCount());
        } catch (RemoteException ex) {
            Logger.getLogger(TelaAgente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attVooActionPerformed

    private void setVoo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setVoo
        // atualiza voo
        campoVoo.setText("");
    }//GEN-LAST:event_setVoo

    private void setHotel(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_setHotel
        // TODO add your handling code here:
        campoHotel.setText("");
    }//GEN-LAST:event_setHotel

    // invoca metodo attPacotes no servidor
    private void attPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attPacoteActionPerformed
        try {
            interface_server.attPacotes(nomePacote.getText(), campoVoo.getText(), campoVooVolta.getText(), campoDataIda.getText(), campoDatavolta.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(TelaAgente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attPacoteActionPerformed

    // invoca metodo attHotel no servidor
    private void attHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attHotelActionPerformed
        // TODO add your handling code here:
        interface_server.attHotel(campoHotel.getText(), nQuartos.getComponentCount(), campoDataIda.getText(), campoDatavolta.getText(), 0);
    }//GEN-LAST:event_attHotelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Agente;
    private java.awt.Button attHotel;
    private java.awt.Button attPacote;
    private java.awt.Button attVoo;
    private java.awt.TextField campoDataIda;
    private java.awt.TextField campoDatavolta;
    private java.awt.TextField campoHotel;
    private java.awt.TextField campoVoo;
    private java.awt.TextField campoVooVolta;
    private java.awt.Label checkIn;
    private java.awt.Label checkOut;
    private java.awt.Checkbox chkPacote;
    private java.awt.TextField dataCheckin;
    private java.awt.TextField dataCheckout;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label3;
    private java.awt.Label labelDataVolta;
    private java.awt.Label labelHotel;
    private javax.swing.JLabel labelPessoas;
    private javax.swing.JLabel labelQuartos;
    private java.awt.Label lavbelVoo;
    private javax.swing.JSpinner nPessoas;
    private javax.swing.JSpinner nQuartos;
    private java.awt.TextField nomePacote;
    // End of variables declaration//GEN-END:variables
}
